// Code generated by entc, DO NOT EDIT.

package viewevent

const (
	// Label holds the string label denoting the viewevent type in the database.
	Label = "view_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPage holds the string denoting the page field in the database.
	FieldPage = "page"
	// FieldIPAddress holds the string denoting the ip_address field in the database.
	FieldIPAddress = "ip_address"
	// FieldEventTime holds the string denoting the event_time field in the database.
	FieldEventTime = "event_time"
	// Table holds the table name of the viewevent in the database.
	Table = "view_events"
)

// Columns holds all SQL columns for viewevent fields.
var Columns = []string{
	FieldID,
	FieldPage,
	FieldIPAddress,
	FieldEventTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
