// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"Blog/ent/migrate"

	"Blog/ent/viewevent"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ViewEvent is the client for interacting with the ViewEvent builders.
	ViewEvent *ViewEventClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ViewEvent = NewViewEventClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		ViewEvent: NewViewEventClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		ViewEvent: NewViewEventClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ViewEvent.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ViewEvent.Use(hooks...)
}

// ViewEventClient is a client for the ViewEvent schema.
type ViewEventClient struct {
	config
}

// NewViewEventClient returns a client for the ViewEvent from the given config.
func NewViewEventClient(c config) *ViewEventClient {
	return &ViewEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `viewevent.Hooks(f(g(h())))`.
func (c *ViewEventClient) Use(hooks ...Hook) {
	c.hooks.ViewEvent = append(c.hooks.ViewEvent, hooks...)
}

// Create returns a create builder for ViewEvent.
func (c *ViewEventClient) Create() *ViewEventCreate {
	mutation := newViewEventMutation(c.config, OpCreate)
	return &ViewEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ViewEvent entities.
func (c *ViewEventClient) CreateBulk(builders ...*ViewEventCreate) *ViewEventCreateBulk {
	return &ViewEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ViewEvent.
func (c *ViewEventClient) Update() *ViewEventUpdate {
	mutation := newViewEventMutation(c.config, OpUpdate)
	return &ViewEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ViewEventClient) UpdateOne(ve *ViewEvent) *ViewEventUpdateOne {
	mutation := newViewEventMutation(c.config, OpUpdateOne, withViewEvent(ve))
	return &ViewEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ViewEventClient) UpdateOneID(id int) *ViewEventUpdateOne {
	mutation := newViewEventMutation(c.config, OpUpdateOne, withViewEventID(id))
	return &ViewEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ViewEvent.
func (c *ViewEventClient) Delete() *ViewEventDelete {
	mutation := newViewEventMutation(c.config, OpDelete)
	return &ViewEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ViewEventClient) DeleteOne(ve *ViewEvent) *ViewEventDeleteOne {
	return c.DeleteOneID(ve.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ViewEventClient) DeleteOneID(id int) *ViewEventDeleteOne {
	builder := c.Delete().Where(viewevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ViewEventDeleteOne{builder}
}

// Query returns a query builder for ViewEvent.
func (c *ViewEventClient) Query() *ViewEventQuery {
	return &ViewEventQuery{
		config: c.config,
	}
}

// Get returns a ViewEvent entity by its id.
func (c *ViewEventClient) Get(ctx context.Context, id int) (*ViewEvent, error) {
	return c.Query().Where(viewevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ViewEventClient) GetX(ctx context.Context, id int) *ViewEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ViewEventClient) Hooks() []Hook {
	return c.hooks.ViewEvent
}
