// Code generated by entc, DO NOT EDIT.

package ent

import (
	"Blog/ent/predicate"
	"Blog/ent/viewevent"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeViewEvent = "ViewEvent"
)

// ViewEventMutation represents an operation that mutates the ViewEvent nodes in the graph.
type ViewEventMutation struct {
	config
	op            Op
	typ           string
	id            *int
	page          *string
	ip_address    *string
	event_time    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ViewEvent, error)
	predicates    []predicate.ViewEvent
}

var _ ent.Mutation = (*ViewEventMutation)(nil)

// vieweventOption allows management of the mutation configuration using functional options.
type vieweventOption func(*ViewEventMutation)

// newViewEventMutation creates new mutation for the ViewEvent entity.
func newViewEventMutation(c config, op Op, opts ...vieweventOption) *ViewEventMutation {
	m := &ViewEventMutation{
		config:        c,
		op:            op,
		typ:           TypeViewEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withViewEventID sets the ID field of the mutation.
func withViewEventID(id int) vieweventOption {
	return func(m *ViewEventMutation) {
		var (
			err   error
			once  sync.Once
			value *ViewEvent
		)
		m.oldValue = func(ctx context.Context) (*ViewEvent, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ViewEvent.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withViewEvent sets the old ViewEvent of the mutation.
func withViewEvent(node *ViewEvent) vieweventOption {
	return func(m *ViewEventMutation) {
		m.oldValue = func(context.Context) (*ViewEvent, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ViewEventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ViewEventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ViewEventMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ViewEventMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ViewEvent.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPage sets the "page" field.
func (m *ViewEventMutation) SetPage(s string) {
	m.page = &s
}

// Page returns the value of the "page" field in the mutation.
func (m *ViewEventMutation) Page() (r string, exists bool) {
	v := m.page
	if v == nil {
		return
	}
	return *v, true
}

// OldPage returns the old "page" field's value of the ViewEvent entity.
// If the ViewEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ViewEventMutation) OldPage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPage: %w", err)
	}
	return oldValue.Page, nil
}

// ResetPage resets all changes to the "page" field.
func (m *ViewEventMutation) ResetPage() {
	m.page = nil
}

// SetIPAddress sets the "ip_address" field.
func (m *ViewEventMutation) SetIPAddress(s string) {
	m.ip_address = &s
}

// IPAddress returns the value of the "ip_address" field in the mutation.
func (m *ViewEventMutation) IPAddress() (r string, exists bool) {
	v := m.ip_address
	if v == nil {
		return
	}
	return *v, true
}

// OldIPAddress returns the old "ip_address" field's value of the ViewEvent entity.
// If the ViewEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ViewEventMutation) OldIPAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIPAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIPAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIPAddress: %w", err)
	}
	return oldValue.IPAddress, nil
}

// ResetIPAddress resets all changes to the "ip_address" field.
func (m *ViewEventMutation) ResetIPAddress() {
	m.ip_address = nil
}

// SetEventTime sets the "event_time" field.
func (m *ViewEventMutation) SetEventTime(t time.Time) {
	m.event_time = &t
}

// EventTime returns the value of the "event_time" field in the mutation.
func (m *ViewEventMutation) EventTime() (r time.Time, exists bool) {
	v := m.event_time
	if v == nil {
		return
	}
	return *v, true
}

// OldEventTime returns the old "event_time" field's value of the ViewEvent entity.
// If the ViewEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ViewEventMutation) OldEventTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEventTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEventTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEventTime: %w", err)
	}
	return oldValue.EventTime, nil
}

// ResetEventTime resets all changes to the "event_time" field.
func (m *ViewEventMutation) ResetEventTime() {
	m.event_time = nil
}

// Where appends a list predicates to the ViewEventMutation builder.
func (m *ViewEventMutation) Where(ps ...predicate.ViewEvent) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *ViewEventMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (ViewEvent).
func (m *ViewEventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ViewEventMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.page != nil {
		fields = append(fields, viewevent.FieldPage)
	}
	if m.ip_address != nil {
		fields = append(fields, viewevent.FieldIPAddress)
	}
	if m.event_time != nil {
		fields = append(fields, viewevent.FieldEventTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ViewEventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case viewevent.FieldPage:
		return m.Page()
	case viewevent.FieldIPAddress:
		return m.IPAddress()
	case viewevent.FieldEventTime:
		return m.EventTime()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ViewEventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case viewevent.FieldPage:
		return m.OldPage(ctx)
	case viewevent.FieldIPAddress:
		return m.OldIPAddress(ctx)
	case viewevent.FieldEventTime:
		return m.OldEventTime(ctx)
	}
	return nil, fmt.Errorf("unknown ViewEvent field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ViewEventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case viewevent.FieldPage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPage(v)
		return nil
	case viewevent.FieldIPAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIPAddress(v)
		return nil
	case viewevent.FieldEventTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventTime(v)
		return nil
	}
	return fmt.Errorf("unknown ViewEvent field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ViewEventMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ViewEventMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ViewEventMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ViewEvent numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ViewEventMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ViewEventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ViewEventMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ViewEvent nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ViewEventMutation) ResetField(name string) error {
	switch name {
	case viewevent.FieldPage:
		m.ResetPage()
		return nil
	case viewevent.FieldIPAddress:
		m.ResetIPAddress()
		return nil
	case viewevent.FieldEventTime:
		m.ResetEventTime()
		return nil
	}
	return fmt.Errorf("unknown ViewEvent field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ViewEventMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ViewEventMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ViewEventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ViewEventMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ViewEventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ViewEventMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ViewEventMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ViewEvent unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ViewEventMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ViewEvent edge %s", name)
}
