// Code generated by entc, DO NOT EDIT.

package ent

import (
	"Blog/ent/viewevent"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ViewEventCreate is the builder for creating a ViewEvent entity.
type ViewEventCreate struct {
	config
	mutation *ViewEventMutation
	hooks    []Hook
}

// SetPage sets the "page" field.
func (vec *ViewEventCreate) SetPage(s string) *ViewEventCreate {
	vec.mutation.SetPage(s)
	return vec
}

// SetIPAddress sets the "ip_address" field.
func (vec *ViewEventCreate) SetIPAddress(s string) *ViewEventCreate {
	vec.mutation.SetIPAddress(s)
	return vec
}

// SetEventTime sets the "event_time" field.
func (vec *ViewEventCreate) SetEventTime(t time.Time) *ViewEventCreate {
	vec.mutation.SetEventTime(t)
	return vec
}

// Mutation returns the ViewEventMutation object of the builder.
func (vec *ViewEventCreate) Mutation() *ViewEventMutation {
	return vec.mutation
}

// Save creates the ViewEvent in the database.
func (vec *ViewEventCreate) Save(ctx context.Context) (*ViewEvent, error) {
	var (
		err  error
		node *ViewEvent
	)
	if len(vec.hooks) == 0 {
		if err = vec.check(); err != nil {
			return nil, err
		}
		node, err = vec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ViewEventMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = vec.check(); err != nil {
				return nil, err
			}
			vec.mutation = mutation
			if node, err = vec.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(vec.hooks) - 1; i >= 0; i-- {
			if vec.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = vec.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vec.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (vec *ViewEventCreate) SaveX(ctx context.Context) *ViewEvent {
	v, err := vec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vec *ViewEventCreate) Exec(ctx context.Context) error {
	_, err := vec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vec *ViewEventCreate) ExecX(ctx context.Context) {
	if err := vec.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vec *ViewEventCreate) check() error {
	if _, ok := vec.mutation.Page(); !ok {
		return &ValidationError{Name: "page", err: errors.New(`ent: missing required field "ViewEvent.page"`)}
	}
	if _, ok := vec.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "ViewEvent.ip_address"`)}
	}
	if _, ok := vec.mutation.EventTime(); !ok {
		return &ValidationError{Name: "event_time", err: errors.New(`ent: missing required field "ViewEvent.event_time"`)}
	}
	return nil
}

func (vec *ViewEventCreate) sqlSave(ctx context.Context) (*ViewEvent, error) {
	_node, _spec := vec.createSpec()
	if err := sqlgraph.CreateNode(ctx, vec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (vec *ViewEventCreate) createSpec() (*ViewEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ViewEvent{config: vec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: viewevent.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: viewevent.FieldID,
			},
		}
	)
	if value, ok := vec.mutation.Page(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: viewevent.FieldPage,
		})
		_node.Page = value
	}
	if value, ok := vec.mutation.IPAddress(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: viewevent.FieldIPAddress,
		})
		_node.IPAddress = value
	}
	if value, ok := vec.mutation.EventTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: viewevent.FieldEventTime,
		})
		_node.EventTime = value
	}
	return _node, _spec
}

// ViewEventCreateBulk is the builder for creating many ViewEvent entities in bulk.
type ViewEventCreateBulk struct {
	config
	builders []*ViewEventCreate
}

// Save creates the ViewEvent entities in the database.
func (vecb *ViewEventCreateBulk) Save(ctx context.Context) ([]*ViewEvent, error) {
	specs := make([]*sqlgraph.CreateSpec, len(vecb.builders))
	nodes := make([]*ViewEvent, len(vecb.builders))
	mutators := make([]Mutator, len(vecb.builders))
	for i := range vecb.builders {
		func(i int, root context.Context) {
			builder := vecb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ViewEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vecb *ViewEventCreateBulk) SaveX(ctx context.Context) []*ViewEvent {
	v, err := vecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vecb *ViewEventCreateBulk) Exec(ctx context.Context) error {
	_, err := vecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vecb *ViewEventCreateBulk) ExecX(ctx context.Context) {
	if err := vecb.Exec(ctx); err != nil {
		panic(err)
	}
}
