// Code generated by entc, DO NOT EDIT.

package ent

import (
	"Blog/ent/predicate"
	"Blog/ent/viewevent"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ViewEventQuery is the builder for querying ViewEvent entities.
type ViewEventQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ViewEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ViewEventQuery builder.
func (veq *ViewEventQuery) Where(ps ...predicate.ViewEvent) *ViewEventQuery {
	veq.predicates = append(veq.predicates, ps...)
	return veq
}

// Limit adds a limit step to the query.
func (veq *ViewEventQuery) Limit(limit int) *ViewEventQuery {
	veq.limit = &limit
	return veq
}

// Offset adds an offset step to the query.
func (veq *ViewEventQuery) Offset(offset int) *ViewEventQuery {
	veq.offset = &offset
	return veq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (veq *ViewEventQuery) Unique(unique bool) *ViewEventQuery {
	veq.unique = &unique
	return veq
}

// Order adds an order step to the query.
func (veq *ViewEventQuery) Order(o ...OrderFunc) *ViewEventQuery {
	veq.order = append(veq.order, o...)
	return veq
}

// First returns the first ViewEvent entity from the query.
// Returns a *NotFoundError when no ViewEvent was found.
func (veq *ViewEventQuery) First(ctx context.Context) (*ViewEvent, error) {
	nodes, err := veq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{viewevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (veq *ViewEventQuery) FirstX(ctx context.Context) *ViewEvent {
	node, err := veq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ViewEvent ID from the query.
// Returns a *NotFoundError when no ViewEvent ID was found.
func (veq *ViewEventQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = veq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{viewevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (veq *ViewEventQuery) FirstIDX(ctx context.Context) int {
	id, err := veq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ViewEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ViewEvent entity is found.
// Returns a *NotFoundError when no ViewEvent entities are found.
func (veq *ViewEventQuery) Only(ctx context.Context) (*ViewEvent, error) {
	nodes, err := veq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{viewevent.Label}
	default:
		return nil, &NotSingularError{viewevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (veq *ViewEventQuery) OnlyX(ctx context.Context) *ViewEvent {
	node, err := veq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ViewEvent ID in the query.
// Returns a *NotSingularError when more than one ViewEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (veq *ViewEventQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = veq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{viewevent.Label}
	default:
		err = &NotSingularError{viewevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (veq *ViewEventQuery) OnlyIDX(ctx context.Context) int {
	id, err := veq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ViewEvents.
func (veq *ViewEventQuery) All(ctx context.Context) ([]*ViewEvent, error) {
	if err := veq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return veq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (veq *ViewEventQuery) AllX(ctx context.Context) []*ViewEvent {
	nodes, err := veq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ViewEvent IDs.
func (veq *ViewEventQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := veq.Select(viewevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (veq *ViewEventQuery) IDsX(ctx context.Context) []int {
	ids, err := veq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (veq *ViewEventQuery) Count(ctx context.Context) (int, error) {
	if err := veq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return veq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (veq *ViewEventQuery) CountX(ctx context.Context) int {
	count, err := veq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (veq *ViewEventQuery) Exist(ctx context.Context) (bool, error) {
	if err := veq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return veq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (veq *ViewEventQuery) ExistX(ctx context.Context) bool {
	exist, err := veq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ViewEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (veq *ViewEventQuery) Clone() *ViewEventQuery {
	if veq == nil {
		return nil
	}
	return &ViewEventQuery{
		config:     veq.config,
		limit:      veq.limit,
		offset:     veq.offset,
		order:      append([]OrderFunc{}, veq.order...),
		predicates: append([]predicate.ViewEvent{}, veq.predicates...),
		// clone intermediate query.
		sql:    veq.sql.Clone(),
		path:   veq.path,
		unique: veq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Page string `json:"page,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ViewEvent.Query().
//		GroupBy(viewevent.FieldPage).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (veq *ViewEventQuery) GroupBy(field string, fields ...string) *ViewEventGroupBy {
	group := &ViewEventGroupBy{config: veq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := veq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return veq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Page string `json:"page,omitempty"`
//	}
//
//	client.ViewEvent.Query().
//		Select(viewevent.FieldPage).
//		Scan(ctx, &v)
//
func (veq *ViewEventQuery) Select(fields ...string) *ViewEventSelect {
	veq.fields = append(veq.fields, fields...)
	return &ViewEventSelect{ViewEventQuery: veq}
}

func (veq *ViewEventQuery) prepareQuery(ctx context.Context) error {
	for _, f := range veq.fields {
		if !viewevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if veq.path != nil {
		prev, err := veq.path(ctx)
		if err != nil {
			return err
		}
		veq.sql = prev
	}
	return nil
}

func (veq *ViewEventQuery) sqlAll(ctx context.Context) ([]*ViewEvent, error) {
	var (
		nodes = []*ViewEvent{}
		_spec = veq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ViewEvent{config: veq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, veq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (veq *ViewEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := veq.querySpec()
	_spec.Node.Columns = veq.fields
	if len(veq.fields) > 0 {
		_spec.Unique = veq.unique != nil && *veq.unique
	}
	return sqlgraph.CountNodes(ctx, veq.driver, _spec)
}

func (veq *ViewEventQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := veq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (veq *ViewEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   viewevent.Table,
			Columns: viewevent.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: viewevent.FieldID,
			},
		},
		From:   veq.sql,
		Unique: true,
	}
	if unique := veq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := veq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, viewevent.FieldID)
		for i := range fields {
			if fields[i] != viewevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := veq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := veq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := veq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := veq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (veq *ViewEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(veq.driver.Dialect())
	t1 := builder.Table(viewevent.Table)
	columns := veq.fields
	if len(columns) == 0 {
		columns = viewevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if veq.sql != nil {
		selector = veq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if veq.unique != nil && *veq.unique {
		selector.Distinct()
	}
	for _, p := range veq.predicates {
		p(selector)
	}
	for _, p := range veq.order {
		p(selector)
	}
	if offset := veq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := veq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ViewEventGroupBy is the group-by builder for ViewEvent entities.
type ViewEventGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vegb *ViewEventGroupBy) Aggregate(fns ...AggregateFunc) *ViewEventGroupBy {
	vegb.fns = append(vegb.fns, fns...)
	return vegb
}

// Scan applies the group-by query and scans the result into the given value.
func (vegb *ViewEventGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := vegb.path(ctx)
	if err != nil {
		return err
	}
	vegb.sql = query
	return vegb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vegb *ViewEventGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := vegb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (vegb *ViewEventGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(vegb.fields) > 1 {
		return nil, errors.New("ent: ViewEventGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := vegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vegb *ViewEventGroupBy) StringsX(ctx context.Context) []string {
	v, err := vegb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vegb *ViewEventGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vegb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewevent.Label}
	default:
		err = fmt.Errorf("ent: ViewEventGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vegb *ViewEventGroupBy) StringX(ctx context.Context) string {
	v, err := vegb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (vegb *ViewEventGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(vegb.fields) > 1 {
		return nil, errors.New("ent: ViewEventGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := vegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vegb *ViewEventGroupBy) IntsX(ctx context.Context) []int {
	v, err := vegb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vegb *ViewEventGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vegb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewevent.Label}
	default:
		err = fmt.Errorf("ent: ViewEventGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vegb *ViewEventGroupBy) IntX(ctx context.Context) int {
	v, err := vegb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (vegb *ViewEventGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(vegb.fields) > 1 {
		return nil, errors.New("ent: ViewEventGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := vegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vegb *ViewEventGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := vegb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vegb *ViewEventGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vegb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewevent.Label}
	default:
		err = fmt.Errorf("ent: ViewEventGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vegb *ViewEventGroupBy) Float64X(ctx context.Context) float64 {
	v, err := vegb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (vegb *ViewEventGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(vegb.fields) > 1 {
		return nil, errors.New("ent: ViewEventGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := vegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vegb *ViewEventGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := vegb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vegb *ViewEventGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vegb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewevent.Label}
	default:
		err = fmt.Errorf("ent: ViewEventGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vegb *ViewEventGroupBy) BoolX(ctx context.Context) bool {
	v, err := vegb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vegb *ViewEventGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range vegb.fields {
		if !viewevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := vegb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vegb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (vegb *ViewEventGroupBy) sqlQuery() *sql.Selector {
	selector := vegb.sql.Select()
	aggregation := make([]string, 0, len(vegb.fns))
	for _, fn := range vegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(vegb.fields)+len(vegb.fns))
		for _, f := range vegb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(vegb.fields...)...)
}

// ViewEventSelect is the builder for selecting fields of ViewEvent entities.
type ViewEventSelect struct {
	*ViewEventQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ves *ViewEventSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ves.prepareQuery(ctx); err != nil {
		return err
	}
	ves.sql = ves.ViewEventQuery.sqlQuery(ctx)
	return ves.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ves *ViewEventSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ves.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ves *ViewEventSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ves.fields) > 1 {
		return nil, errors.New("ent: ViewEventSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ves.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ves *ViewEventSelect) StringsX(ctx context.Context) []string {
	v, err := ves.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ves *ViewEventSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ves.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewevent.Label}
	default:
		err = fmt.Errorf("ent: ViewEventSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ves *ViewEventSelect) StringX(ctx context.Context) string {
	v, err := ves.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ves *ViewEventSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ves.fields) > 1 {
		return nil, errors.New("ent: ViewEventSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ves.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ves *ViewEventSelect) IntsX(ctx context.Context) []int {
	v, err := ves.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ves *ViewEventSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ves.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewevent.Label}
	default:
		err = fmt.Errorf("ent: ViewEventSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ves *ViewEventSelect) IntX(ctx context.Context) int {
	v, err := ves.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ves *ViewEventSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ves.fields) > 1 {
		return nil, errors.New("ent: ViewEventSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ves.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ves *ViewEventSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ves.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ves *ViewEventSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ves.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewevent.Label}
	default:
		err = fmt.Errorf("ent: ViewEventSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ves *ViewEventSelect) Float64X(ctx context.Context) float64 {
	v, err := ves.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ves *ViewEventSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ves.fields) > 1 {
		return nil, errors.New("ent: ViewEventSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ves.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ves *ViewEventSelect) BoolsX(ctx context.Context) []bool {
	v, err := ves.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ves *ViewEventSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ves.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewevent.Label}
	default:
		err = fmt.Errorf("ent: ViewEventSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ves *ViewEventSelect) BoolX(ctx context.Context) bool {
	v, err := ves.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ves *ViewEventSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ves.sql.Query()
	if err := ves.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
