// Code generated by entc, DO NOT EDIT.

package ent

import (
	"Blog/ent/predicate"
	"Blog/ent/viewevent"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ViewEventDelete is the builder for deleting a ViewEvent entity.
type ViewEventDelete struct {
	config
	hooks    []Hook
	mutation *ViewEventMutation
}

// Where appends a list predicates to the ViewEventDelete builder.
func (ved *ViewEventDelete) Where(ps ...predicate.ViewEvent) *ViewEventDelete {
	ved.mutation.Where(ps...)
	return ved
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ved *ViewEventDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ved.hooks) == 0 {
		affected, err = ved.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ViewEventMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ved.mutation = mutation
			affected, err = ved.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ved.hooks) - 1; i >= 0; i-- {
			if ved.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ved.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ved.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ved *ViewEventDelete) ExecX(ctx context.Context) int {
	n, err := ved.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ved *ViewEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: viewevent.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: viewevent.FieldID,
			},
		},
	}
	if ps := ved.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ved.driver, _spec)
}

// ViewEventDeleteOne is the builder for deleting a single ViewEvent entity.
type ViewEventDeleteOne struct {
	ved *ViewEventDelete
}

// Exec executes the deletion query.
func (vedo *ViewEventDeleteOne) Exec(ctx context.Context) error {
	n, err := vedo.ved.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{viewevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vedo *ViewEventDeleteOne) ExecX(ctx context.Context) {
	vedo.ved.ExecX(ctx)
}
